### ISSUE TITLE
No branch name corresponding to the position(data-scientist-intern-2020-Q3) for submitting a PR

### ISSUE THREAD

**Issue by praxalpatel** [bomboradata/datascience-exam#100]
My ds-position is data-scientist-intern-2020-Q3. When trying to send a pull request, I was not able to find data-scientist-intern-2020-Q3-submittals branch

**Comment by NahsiN** [comment]
Thank you for bringing this to my attention. I'll look into this with my colleagues. In the meantime, I acknowledge receiving your exam as an attachment.

**Comment by NahsiN** [comment]
Branch data-scientist-intern-2020-Q3 has been created. Thanks again for reporting.
