### ISSUE TITLE
No branch name data-scientist-intern-2020-Q3-submittals for PR

### ISSUE THREAD

**Issue by benberkman** [bomboradata/datascience-exam#112]
I see this issue was previously brought up and closed. However, I do not see the branch corresponding to data-scientist-intern-2020-Q3. Has this branch been deleted? Thank you.

**Comment by NahsiN** [comment]
@benberkman Thank you for bringing this to our attention, this was due to a Greenhouse error on our part. The branch `data-scientist-intern-2020-Q3`
https://github.com/bomboradata/datascience-exam/tree/data-scientist-intern-2020-Q3  has been re-created.
