### ISSUE TITLE
Similar question for branch names

### ISSUE THREAD

**Issue by yuwei-jacque-wang** [bomboradata/datascience-exam#113]
Similar question with others: 
1. I see the brach is named data-scientist-intern-2021-spring (instead of 2020-Q3) should we just use this one?
2. For Pull Request there's no branch with -submittals, so should I just PR to data-scientist-intern-2021-spring? 
Thanks!

**Comment by NahsiN** [comment]
Hi @yuwei-jacque-wang, you're correct, please submit PR to `data-scientist-intern-2021-spring`

**Comment by yuwei-jacque-wang** [comment]
Great, thanks!
