### ISSUE TITLE
Having trouble creating exam directory

### ISSUE THREAD

**Issue by rebeccaisnotabug** [bomboradata/datascience-exam#128]
When I tried to create my exam directory using `mkdir ./submittals/$DS_POSITION/$DS_EXAM_NAME`, it showed an error "mkdir: ./submittals/data-scientist-intern-2021-Q3: No such file or directory". I was wondering how to solve this issue? Thanks!

<img width="738" alt="Screen Shot 2021-04-21 at 16 04 24" src="https://user-images.githubusercontent.com/54948582/115614816-20a27080-a2bc-11eb-9f54-81881c425ca9.png">

**Comment by NahsiN** [comment]
Thanks for brining this to my attention. The issue was around the submittals directory not being present. This has been fixed.
