### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by legends-sandbox** [bomboradata/datascience-exam#77]
When I attempted to clone datascience-exam with the following command:
`git clone git@github.com:$GH_USERNAME/datascience-exam.git`
I get the following error:
"git@github.com: Permission denied (publickey). fatal: Could not read from remote repository"

Has the URL changed or do I need to be granted permission?

**Comment by nehalecky** [comment]
Hi @legends-sandbox, did you make sure you have your s[sh keys setup correctly](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/) with your GH account?

**Comment by nehalecky** [comment]
@GraceShanGuo, I suspect that you might not have forked it! Regardless, thanks for you submission!
